#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarm_Tec_Service.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GRID")]
	public partial class AlarmTecDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAlarmTec_User(AlarmTec_User instance);
    partial void UpdateAlarmTec_User(AlarmTec_User instance);
    partial void DeleteAlarmTec_User(AlarmTec_User instance);
    partial void InsertAlarmTec_Alarm(AlarmTec_Alarm instance);
    partial void UpdateAlarmTec_Alarm(AlarmTec_Alarm instance);
    partial void DeleteAlarmTec_Alarm(AlarmTec_Alarm instance);
    #endregion
		
		public AlarmTecDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GRIDConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AlarmTecDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlarmTecDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlarmTecDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlarmTecDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AlarmTec_User> AlarmTec_Users
		{
			get
			{
				return this.GetTable<AlarmTec_User>();
			}
		}
		
		public System.Data.Linq.Table<AlarmTec_Alarm> AlarmTec_Alarms
		{
			get
			{
				return this.GetTable<AlarmTec_Alarm>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlarmTec_Users")]
	public partial class AlarmTec_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private string _UserEmail;
		
		private string _UserPassword;
		
		private System.DateTime _UserCreateDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnUserEmailChanging(string value);
    partial void OnUserEmailChanged();
    partial void OnUserPasswordChanging(string value);
    partial void OnUserPasswordChanged();
    partial void OnUserCreateDateChanging(System.DateTime value);
    partial void OnUserCreateDateChanged();
    #endregion
		
		public AlarmTec_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserEmail", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string UserEmail
		{
			get
			{
				return this._UserEmail;
			}
			set
			{
				if ((this._UserEmail != value))
				{
					this.OnUserEmailChanging(value);
					this.SendPropertyChanging();
					this._UserEmail = value;
					this.SendPropertyChanged("UserEmail");
					this.OnUserEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPassword", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string UserPassword
		{
			get
			{
				return this._UserPassword;
			}
			set
			{
				if ((this._UserPassword != value))
				{
					this.OnUserPasswordChanging(value);
					this.SendPropertyChanging();
					this._UserPassword = value;
					this.SendPropertyChanged("UserPassword");
					this.OnUserPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime UserCreateDate
		{
			get
			{
				return this._UserCreateDate;
			}
			set
			{
				if ((this._UserCreateDate != value))
				{
					this.OnUserCreateDateChanging(value);
					this.SendPropertyChanging();
					this._UserCreateDate = value;
					this.SendPropertyChanged("UserCreateDate");
					this.OnUserCreateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlarmTec_Alarms")]
	public partial class AlarmTec_Alarm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AlarmId;
		
		private int _UserId;
		
		private System.DateTime _AlarmCreateDate;
		
		private string _AlarmWakeUpTime;
		
		private System.Nullable<bool> _AlarmWantsNews;
		
		private System.Nullable<bool> _AlarmWantsWeather;
		
		private System.Nullable<bool> _AlarmIsEnabled;
		
		private string _AlarmName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAlarmIdChanging(int value);
    partial void OnAlarmIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnAlarmCreateDateChanging(System.DateTime value);
    partial void OnAlarmCreateDateChanged();
    partial void OnAlarmWakeUpTimeChanging(string value);
    partial void OnAlarmWakeUpTimeChanged();
    partial void OnAlarmWantsNewsChanging(System.Nullable<bool> value);
    partial void OnAlarmWantsNewsChanged();
    partial void OnAlarmWantsWeatherChanging(System.Nullable<bool> value);
    partial void OnAlarmWantsWeatherChanged();
    partial void OnAlarmIsEnabledChanging(System.Nullable<bool> value);
    partial void OnAlarmIsEnabledChanged();
    partial void OnAlarmNameChanging(string value);
    partial void OnAlarmNameChanged();
    #endregion
		
		public AlarmTec_Alarm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlarmId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AlarmId
		{
			get
			{
				return this._AlarmId;
			}
			set
			{
				if ((this._AlarmId != value))
				{
					this.OnAlarmIdChanging(value);
					this.SendPropertyChanging();
					this._AlarmId = value;
					this.SendPropertyChanged("AlarmId");
					this.OnAlarmIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlarmCreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime AlarmCreateDate
		{
			get
			{
				return this._AlarmCreateDate;
			}
			set
			{
				if ((this._AlarmCreateDate != value))
				{
					this.OnAlarmCreateDateChanging(value);
					this.SendPropertyChanging();
					this._AlarmCreateDate = value;
					this.SendPropertyChanged("AlarmCreateDate");
					this.OnAlarmCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlarmWakeUpTime", DbType="VarChar(50)")]
		public string AlarmWakeUpTime
		{
			get
			{
				return this._AlarmWakeUpTime;
			}
			set
			{
				if ((this._AlarmWakeUpTime != value))
				{
					this.OnAlarmWakeUpTimeChanging(value);
					this.SendPropertyChanging();
					this._AlarmWakeUpTime = value;
					this.SendPropertyChanged("AlarmWakeUpTime");
					this.OnAlarmWakeUpTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlarmWantsNews", DbType="Bit")]
		public System.Nullable<bool> AlarmWantsNews
		{
			get
			{
				return this._AlarmWantsNews;
			}
			set
			{
				if ((this._AlarmWantsNews != value))
				{
					this.OnAlarmWantsNewsChanging(value);
					this.SendPropertyChanging();
					this._AlarmWantsNews = value;
					this.SendPropertyChanged("AlarmWantsNews");
					this.OnAlarmWantsNewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlarmWantsWeather", DbType="Bit")]
		public System.Nullable<bool> AlarmWantsWeather
		{
			get
			{
				return this._AlarmWantsWeather;
			}
			set
			{
				if ((this._AlarmWantsWeather != value))
				{
					this.OnAlarmWantsWeatherChanging(value);
					this.SendPropertyChanging();
					this._AlarmWantsWeather = value;
					this.SendPropertyChanged("AlarmWantsWeather");
					this.OnAlarmWantsWeatherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlarmIsEnabled", DbType="Bit")]
		public System.Nullable<bool> AlarmIsEnabled
		{
			get
			{
				return this._AlarmIsEnabled;
			}
			set
			{
				if ((this._AlarmIsEnabled != value))
				{
					this.OnAlarmIsEnabledChanging(value);
					this.SendPropertyChanging();
					this._AlarmIsEnabled = value;
					this.SendPropertyChanged("AlarmIsEnabled");
					this.OnAlarmIsEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlarmName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AlarmName
		{
			get
			{
				return this._AlarmName;
			}
			set
			{
				if ((this._AlarmName != value))
				{
					this.OnAlarmNameChanging(value);
					this.SendPropertyChanging();
					this._AlarmName = value;
					this.SendPropertyChanged("AlarmName");
					this.OnAlarmNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
